export enum Seccion {
  Usuarios = 1,
  Pais = 2,
  Instrumento = 3,
  Artista = 4,
  Grupo = 5,
  Disquera = 6,
  Album = 7,
  Cancion = 8,
  ArtistaGrupo = 9,
  CancionAlbum = 10,
  InstrumentoArtistaGrupo = 11,
  Bitacora = 12,
  OtrosProyectos = 13,
}
